# Tuning for the Heron PID controller (for Gazebo simulation)
# max -> see heron_constants.h

fwd_vel:
  kf: 0.0
  kp: 150.0
  ki: 45.0
  kd: 5.0
  imax: +100.0
  imin: -100.0

yaw_rate:
  kf: 0.0
  kp: 200.0
  ki: 30.0
  kd: 5.0
  imax: +100.0
  imin: -100.0

yaw:
  kf: 0.0
  kp: 3.0
  ki: 0.0
  kd: 0.2
  imax: 0.0
  imin: 0.0

cov_limits:
  imu: 1.0
  velocity: 0.3

max:
  fwd_vel: 2.0
  bck_vel: 0.5

timeout:
  imu_data: 0.2
  vel_data: 0.2

  course_cmd: 0.5
  helm_cmd: 0.5
  wrench_cmd: 0.5
  twist_cmd: 1.5
